<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>k</string>
	</array>
	<key>name</key>
	<string>K-Framework</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(require)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.import.k-framework</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\s*$</string>
			<key>name</key>
			<string>meta.require.k-framework</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(module)\s+([a-zA-Z0-9_-]+)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.module.k-framework</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.module.k-framework</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^\s*(end(?:\s)*module)\s*$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.endmodule.k-framework</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.module.k-framework</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#imports</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#syntax</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#macro</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#configuration</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rule</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#define</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>args-attr</key>
		<dict>
			<key>begin</key>
			<string>([a-zA-Z_-])(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.k-framework</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.begin.attribute.k-framework</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.end.attribute.k-framework</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.attribute.k-framework</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?=[a-zA-Z0-9#\"])</string>
					<key>end</key>
					<string>(,)|(?=\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.arguments.attribute.k-framework</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.attribute.argument.k-framework</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#number</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#syntax-term-nonterminal</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#syntax-term-terminal</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>attr</key>
		<dict>
			<key>begin</key>
			<string>(?=[a-zA-Z])</string>
			<key>end</key>
			<string>(,)|(?=\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.parameters.attributes.k-framework</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.attribute.k-framework</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#latex-attr</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#empty-attr</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#args-attr</string>
				</dict>
			</array>
		</dict>
		<key>attr-args</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.integer.decimal.k-framework</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.attribute.k-framework</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.arguments.k-framework</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.integer.decimal.k-framework</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.language.attribute.k-framework</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(([0-9]+)|([\w-_]+))(?:(,)(([0-9]+)|([\w-_]+)))*</string>
			<key>name</key>
			<string>meta.attributes.arguments.k-framework</string>
		</dict>
		<key>attrs</key>
		<dict>
			<key>begin</key>
			<string>(\[)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.attributes.k-framework</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.attributes.k-framework</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.attributes.k-framework</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#attr</string>
				</dict>
			</array>
		</dict>
		<key>br</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.br.k-framework</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.br.k-framework</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\&lt;(br)\/\&gt;)</string>
			<key>name</key>
			<string>punctuation.definition.tag</string>
		</dict>
		<key>cell</key>
		<dict>
			<key>begin</key>
			<string>(&lt;([\w]+)\s*([^&gt;]+)?&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.cell.k-framework</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.cell.k-framework</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#cell-attr</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>end</key>
			<string>(&lt;/(\2)&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.cell.k-framework</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.cell.k-framework</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.configuration.cell.k-framework</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#br</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cell</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#value</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#syntax-term-nonterminal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#syntax-term-terminal</string>
				</dict>
			</array>
		</dict>
		<key>cell-attr</key>
		<dict>
			<key>begin</key>
			<string>([a-z]+)\s*(=)\s*</string>
			<key>end</key>
			<string>(?=[a-z\&gt;])</string>
			<key>name</key>
			<string>meta.cell.attribute</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.line.k-framework</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(//)[^@].*$</string>
					<key>name</key>
					<string>comment.line.k-framework</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.line.documentation.k-framework</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>text.tex.latex</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>text.tex.latex</string>
								</dict>
							</array>
						</dict>
					</dict>
					<key>match</key>
					<string>(//@)(.*)$</string>
					<key>name</key>
					<string>comment.line.documentation.k-framework</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(/\*)[^@]</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.block.begin.k-framework</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\*/)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.block.end.k-framework</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.k-framework</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(/\*@)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.block.documentation.begin.k-framework</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>text.tex.latex</string>
					<key>end</key>
					<string>(\*/)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.block.documentation.end.k-framework</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.documentation.k-framework</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.tex.latex</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>configuration</key>
		<dict>
			<key>begin</key>
			<string>(configuration)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.def.configuration.k-framework</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=(?:\s*[a-z]))</string>
			<key>name</key>
			<string>meta.configuration.k-framework</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cell</string>
				</dict>
			</array>
		</dict>
		<key>define</key>
		<dict>
			<key>begin</key>
			<string>(define)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.def.define.k-framework</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.define.k-framework</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=(?:\s*(?!(?:when)|(?:where))[a-z]))</string>
			<key>name</key>
			<string>meta.define.k-framework</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>match</key>
					<string>when</string>
					<key>name</key>
					<string>keyword.control.def.rule.when</string>
				</dict>
				<dict>
					<key>match</key>
					<string>where</string>
					<key>name</key>
					<string>keyword.control.def.rule.where</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rule-cell</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attrs</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rewrites</string>
				</dict>
			</array>
		</dict>
		<key>empty-attr</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.k-framework</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([a-zA-Z_-])(?!\()</string>
			<key>name</key>
			<string>meta.attribute.k-framework</string>
		</dict>
		<key>functor-args</key>
		<dict>
			<key>name</key>
			<string>meta.terminal.functor.arguments.k-framework</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.separator.functor.arguments.k-framework</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#value</string>
				</dict>
			</array>
		</dict>
		<key>imports</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.import.k-framework</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.type.module.k-framework</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(imports)\s+(\#?[a-zA-Z0-9_-]+)\s*$</string>
			<key>name</key>
			<string>meta.import.k-framework</string>
		</dict>
		<key>latex-attr</key>
		<dict>
			<key>begin</key>
			<string>(latex)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.latex.k-framework</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.begin.attribute.k-framework</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>text.tex.latex</string>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.end.attribute.k-framework</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.attribute.latex.k-framework</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.tex.latex</string>
				</dict>
			</array>
		</dict>
		<key>macro</key>
		<dict>
			<key>begin</key>
			<string>^\s*(macro)\s+</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.def.macro.k-framework</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=(?:\s*[a-z]))</string>
			<key>name</key>
			<string>meta.structure.macro.k-framework</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>=</string>
					<key>name</key>
					<string>punctuation.definition.macro.output.k-framework</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rewrites</string>
				</dict>
			</array>
		</dict>
		<key>number</key>
		<dict>
			<key>match</key>
			<string>[0-9]+</string>
			<key>name</key>
			<string>constant.numeric.integer.decimal.k-framework</string>
		</dict>
		<key>rewrites</key>
		<dict>
			<key>name</key>
			<string>meta.rewrite.k-framework</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\=\&gt;</string>
					<key>name</key>
					<string>punctuation.definition.function.arrow.rewrite.k-framework</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\~\&gt;</string>
					<key>name</key>
					<string>punctuation.separator.continuation.arrow.next.k-framework</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#value</string>
				</dict>
			</array>
		</dict>
		<key>rule</key>
		<dict>
			<key>begin</key>
			<string>(rule)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.def.rule.k-framework</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.rule.k-framework</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=(?:\s*(?!(?:when)|(?:where))[a-z]))</string>
			<key>name</key>
			<string>meta.rule.k-framework</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>match</key>
					<string>when</string>
					<key>name</key>
					<string>keyword.control.def.rule.when</string>
				</dict>
				<dict>
					<key>match</key>
					<string>where</string>
					<key>name</key>
					<string>keyword.control.def.rule.where</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rule-cell</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attrs</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rewrites</string>
				</dict>
			</array>
		</dict>
		<key>rule-cell</key>
		<dict>
			<key>begin</key>
			<string>(&lt;([\w]+)&gt;)\s*(\.\.\.)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.cell.k-framework</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.cell.k-framework</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.placeholder.before.k-framework</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\.\.\.)?\s*(&lt;/(\2)&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.placeholder.after.k-framework</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.cell.k-framework</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.cell.k-framework</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.rule.cell.k-framework</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rule-cell</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rewrites</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.k-framework</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\</string>
					<key>name</key>
					<string>constant.character.escape.k-framework</string>
				</dict>
			</array>
		</dict>
		<key>syntax</key>
		<dict>
			<key>begin</key>
			<string>^\s*(syntax)\s+(\#?[A-Z][A-Za-z]*)\s*(\:\:\=)\s</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.def.syntax.k-framework</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.syntax.k-framework</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.syntax.definition.k-framework</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=(?:\s*[a-z]))</string>
			<key>name</key>
			<string>meta.structure.syntax.k-framework</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#syntax-term</string>
				</dict>
			</array>
		</dict>
		<key>syntax-term</key>
		<dict>
			<key>begin</key>
			<string>\s*(?:(\|)|(\&gt;)|(\&lt;))?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.syntax.definition.alternation.k-framework</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.syntax.definition.alternation.precedence.lower.k-framework</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.syntax.definition.alternation.precedence.higher.k-framework</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?:(?=[\|\&gt;\&lt;])|^(?=\s*[a-z]))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.begin.attributes.k-framework</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.attributes.k-framework</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#attrs</string>
						</dict>
					</array>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.end.attributes.k-framework</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.structure.syntax.alternative.k-framework</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attrs</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#syntax-term-nonterminal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#syntax-term-terminal</string>
				</dict>
			</array>
		</dict>
		<key>syntax-term-nonterminal</key>
		<dict>
			<key>match</key>
			<string>\#?[A-Z][a-z0-9_-]*</string>
			<key>name</key>
			<string>entity.other.type.syntax.k-framework</string>
		</dict>
		<key>syntax-term-terminal</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?!&lt;/)(?!:[A-Z])(?!_[\s:])(?!\=\&gt;)(?!\~\&gt;)([\,\|]|(?:(?:['.*\-/+`:\^_=?\&gt;&lt;]+)|(?:(?=\b)[a-z]))[a-zA-Z0-9_\-]*)(?&lt;!\,\_)(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.other.syntax.terminal.k-framework</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.begin.terminal.k-framework</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.begin.terminal.k-framework</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.terminal.functor.k-framework</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#functor-args</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#syntax-term-terminal-basic</string>
				</dict>
			</array>
		</dict>
		<key>syntax-term-terminal-basic</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.[A-Z][a-zA-Z0-9_-]+</string>
					<key>name</key>
					<string>entity.other.type.syntax.unit.k-framework</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.other.syntax.terminal.k-framework</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?!&lt;/)(?!:[A-Z])(?!_[\s:])(?!\=\&gt;)(?!\~\&gt;)([\,\|]|(?:(?:[_'.*`\-/+:\^=?\|&gt;&lt;]+)|(?:(?=\b)[a-z]))[a-zA-Z0-9_\-]*)(?&lt;!\,\_)(?&lt;!\()</string>
					<key>name</key>
					<string>meta.terminal.k-framework</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.terminal.k-framework</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string</string>
							<key>name</key>
							<string>string.quoted.double.syntax.terminal.k-framework</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>value</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.predefined.program.k-framework</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.sort.k-framework</string>
						</dict>
						<key>3</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#syntax-term-nonterminal</string>
								</dict>
							</array>
						</dict>
					</dict>
					<key>match</key>
					<string>(\$PGM)(?:(:)\s*([A-Z][a-zA-Z0-9_-]+))?</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.k-framework</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.sort.k-framework</string>
						</dict>
						<key>3</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#syntax-term-nonterminal</string>
								</dict>
							</array>
						</dict>
					</dict>
					<key>match</key>
					<string>([A-Z_][a-zA-Z0-9_\-]*'?)(?:(:)\s*([A-Z][a-zA-Z0-9_-]+))?</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\s\.\s</string>
					<key>name</key>
					<string>entity.other.type.syntax.unit.generic.k-framework</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#syntax-term-terminal</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.k-framework</string>
	<key>uuid</key>
	<string>5A91112C-151A-465E-B21A-0529852DEEED</string>
</dict>
</plist>
